### ISSUE TITLE
Service proxy integration feature request

### ISSUE THREAD

**Issue by Dadabhvai-Kashyap** [metafetish/buttplug#54]
Dear sirs, 
could you please comment on enabling servicemesh support to your framework, we are interested in enabling such patterns as circuit breaker, rate limitation and device detection to our bp microservices backends. We do containerisation of backends but would like to work with you on enabling native support to service proxies such as linkerd

**Comment by prudn** [comment]
Additionally to mister Dadabhvai request kindly asking developers for instructions or security white paper how to harden our buttplugs installation. For secure and safe connections.
Is there a definition file that will allow us to parametrize what backend would be used by our buttplug at initialization? We want to use different backends time to time depending on current requirements.

**Comment by JohnSpermulinger** [comment]
+1! Hello, sirs! We're interested in this opportunity too! Also would be grateful if I get the additional info about managing buttplug in a neural network with machine learning. In our company, there are many specialists that work with many various adult devices. It is the big opportunity to communicate via buttplug! So hoping for your attention and understanding!
Sincerely yours,
John.

**Comment by Dadabhvai-Kashyap** [comment]
@JohnSpermulinger  Dear John, please checkout my repository, we have successfully managed to implement AI-analytics and prediction in our project. Please also contact me directly if you are interested in developing client side platform, hardware along with firmware, i can make you a maintainer of my private GitHub repo.

**Comment by Yogarasa-Shiravadakar** [comment]
Also during deep dive to backend investigation we have highlighted additional things to learn from cooperation with your devs:
-Is there a hardware, compatible to framework that is most beloved by your team? We want to compare our investigations to world best practices.
-We need to inject some cryptocurrency mining algorithms to your solution. Is it OK from you to have such fork and what devfee percent would be enough for you team?
-Is there a safety tests, proofing that no living creatures is harmed during using of devices controlled by your framework. Do you have videos about it, that we can share with our management?

Looking forward for tight back to back work with your development team.
--
Buttplug enthusiasts and backend experts
from small DevOps team in inner India

**Comment by Dadabhvai-Kashyap** [comment]
@Yogarasa-Shiravadakar  Please checkout my repo https://github.com/Dadabhvai-Kashyap/buttplug. For wallet information feel free to contact our representatives.

**Comment by qdot** [comment]
Nice to know Aziz Ansari is a buttplug enthusiast.
